const SET_TOKEN = 'SET_TOKEN';
const SET_LOGGEDIN = 'SET_LOGGEDIN';
const SET_USERDATA = 'SET_USERDATA';
const SET_CARRIER = 'SET_CARRIER';
const SET_LOGO = 'SET_LOGO';

export {SET_TOKEN, SET_LOGGEDIN, SET_USERDATA, SET_CARRIER, SET_LOGO};